type ContractResponse = enum {
  GreenReceived,
  YellowReceived,
  RedReceived,
};

type IoContractState = struct {
  owner: actor_id,
  current_light: Light,
  callers: vec struct { actor_id, Light },
};

type Light = enum {
  Green,
  Red,
  Yellow,
};

type KeyringData = struct {
  address: str,
  encoded: str,
};

type KeyringEvent = enum {
  KeyringAccountSet,
  Error: KeyringError,
};

type KeyringError = enum {
  KeyringAddressAlreadyEsists,
  UserAddressAlreadyExists,
  UserCodedNameAlreadyExists,
  UserDoesNotHasKeyringAccount,
  KeyringAccountAlreadyExists,
  SessionHasInvalidCredentials,
  UserAndKeyringAddressAreTheSame,
};

type KeyringQueryEvent = enum {
  KeyringAccountAddress: opt actor_id,
  KeyringAccountData: opt KeyringData,
};

constructor {
  New : ();
};

service TrafficLight {
  Green : () -> ContractResponse;
  Red : () -> ContractResponse;
  Yellow : () -> ContractResponse;
  query ContractOwner : () -> actor_id;
  query TrafficLight : () -> IoContractState;
};

service KeyringService {
  BindKeyringDataToUserAddress : (user_address: actor_id, keyring_data: KeyringData) -> KeyringEvent;
  BindKeyringDataToUserCodedName : (user_coded_name: str, keyring_data: KeyringData) -> KeyringEvent;
  query KeyringAccountData : (keyring_address: actor_id) -> KeyringQueryEvent;
  query KeyringAddressFromUserAddress : (user_address: actor_id) -> KeyringQueryEvent;
  query KeyringAddressFromUserCodedName : (user_coded_name: str) -> KeyringQueryEvent;
};